name: Build libclangjs

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: emscripten/emsdk

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          pwd
